### ISSUE TITLE
QBEC fails on empty annotations

### ISSUE THREAD

**Issue by kvaps** [splunk/qbec#100]
Example component:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: asd-stolon-proxy
  labels:
    app: stolon
    chart: stolon-1.1.2
    release: asd
    heritage: Tiller
  annotations:
spec:
  type: ClusterIP
  ports:
    - name: proxy
      port: 5432
      protocol: TCP
      targetPort: 5432
      
  selector:
    app: stolon
    release: asd
    component: stolon-proxy
```

```bash
# qbec show default
✘ /v1, Kind=Service, Name=asd-stolon-proxy: .metadata.annotations accessor error: <nil> is of the type <nil>, expected map[string]interface{}
```
