### ISSUE TITLE
Qbec apply label sync does not remove unspecified labels

### ISSUE THREAD

**Issue by e-zhang** [splunk/qbec#114]
When migrating from `ks` to `qbec` for managing deployment of kubernetes objects, it appears that old labels added by `ks` are still preserved after an `apply`.

In the output of `qbec` we see something like

```
sync prometheusrules myrules (source prometheusrules)
kind: application/merge-patch+json
operation: update object
patch: |-
{
      "metadata": {
           "annotations": {
               "qbec.io/component": "mycomponent",
               "qbec.io/last-applied": "...",
          },
           "labels": {
               "app": "myapp",
               "qbec.io/application": "myapp",
               "qbec.io/environment": "myenv",
               "version": "0.9.3"           
         }       
    }   
}
```

in the corresponding object we still see the original labels that are no longer specified

```
  metadata:
    annotations:
      ksonnet.io/managed: '...'
      qbec.io/component: prometheusrules
      qbec.io/last-applied: ..
    creationTimestamp: "2019-01-25T00:38:50Z"
    generation: 4
    labels:
      app: myapp
      app.kubernetes.io/deploy-manager: ksonnet
      ksonnet.io/component: mycomponent
      qbec.io/application: myapp
      qbec.io/environment: myenv
```

so it appears there are leftover annotations and labels from the previous deploy of this object that did not get removed.
