### ISSUE TITLE
Add ability to override qbec vars with env alone

### ISSUE THREAD

**Issue by harsimranmaan** [splunk/qbec#142]
At the moment, env var KEY can be used to set value for a qbec var named KEY but only if --vm:ext-str KEY is specified when invoking qbec command. The enhancement is to drop the requirement on specifying --vm-ext-str KEY.

With the following example from qbec.yaml, both qbec commands below should set the same value for `std.extVar('KEY')`
```yaml
  vars:
    external:
    - default: some-default-key
      name: KEY
```

```bash
export KEY=mykey
qbec show default --vm-ext-str KEY
qbec show default
```
