### ISSUE TITLE
stringData is not obfuscated

### ISSUE THREAD

**Issue by kvaps** [splunk/qbec#162]
Kubernetes allows to use `stringData` instead of `data` for the secrets.
The data passed via `stringData` might be in clear text.

Usually qbec is hiding all confidential information from the output but not the `stringData`.
example component `test.yaml`:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  config.yaml: |-
    apiUrl: "https://my.api.com/api/v1"
    username: "dr.who"
    password: "supersecretpassword"
```

yelds to:

```yaml
---
apiVersion: v1
data: {}
kind: Secret
metadata:
  annotations:
    qbec.io/component: test
  labels:
    qbec.io/application: argocd
    qbec.io/environment: stage-admin
  name: mysecret
stringData:
  config.yaml: |-
    apiUrl: "https://my.api.com/api/v1"
    username: "dr.who"
    password: "supersecretpassword"
type: Opaque
```
