### ISSUE TITLE
Add qbec.io/component to labels

### ISSUE THREAD

**Issue by korroot** [splunk/qbec#180]
I was wondering why `qbec.io/component` is added only to annotations?
Can `qbec.io/component` be added to labels?
Is it something that can be implemented or maybe there are known issues why it is not added to labels already?

My use-case is to integrate ArgoCD with qbec, and I want to have ArgoCD app per qbec component created.

Current state:
```
metadata:
  annotations:
    qbec.io/component: my-component
  labels:
    qbec.io/application: myapplication
    qbec.io/environment: default
  name: my-name
  namespace: my-namespace
```

Desired state:
```
metadata:
  annotations:
    qbec.io/component: my-component
  labels:
    qbec.io/application: myapplication
    qbec.io/component: my-component
    qbec.io/environment: default
  name: my-name
  namespace: my-namespace
```
