### ISSUE TITLE
Pass environment config to the executing command for computed vars

### ISSUE THREAD

**Issue by harsimranmaan** [splunk/qbec#230]
```yaml
    computed:
      - name:cmd
        code: |
          {
            command: 'foo',
            args: [ 'bar', ],
          }
```

If the env map is supplied, it should be merged into the default env config. This is useful for passing secrets, PATH variable etc from the executing environment without having to explicitly specify all env keys in code block.
