### ISSUE TITLE
exec plugin: invalid apiVersion "client.authentication.k8s.io/v1beta1"

### ISSUE THREAD

**Issue by deadNightTiger** [splunk/qbec#83]
My `$HOME/.kube/config`:
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: "<snip>"
    server: "<snip>"
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    namespace: default
    user: oidc
  name: oidc@kubernetes
current-context: oidc@kubernetes
kind: Config
preferences: {}
users:
- name: oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --oidc-issuer-url=<snip>
      - --oidc-client-id=kubernetes
      - --oidc-extra-scope=email
      - --oidc-extra-scope=groups
      command: kubelogin
```

qbec's output (for any subcommand communicating with the cluster):
```
setting cluster to kubernetes
setting context to oidc@kubernetes
✘ exec plugin: invalid apiVersion "client.authentication.k8s.io/v1beta1"
```

Maybe it's time to update client-go?
